name: Publish Docker image

on:
  push

jobs:
  push_to_registries:
    name: Push Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER2 }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/xaos613/docker_build:1
    
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
         SLACK_CHANNEL: general
         SLACK_COLOR: ${{ job.status }}
         SLACK_ICON: https://github.com/rtCamp.png?size=48
         SLACK_MESSAGE: 'Post Content :rocket:'
         SLACK_TITLE: 'Looks like job is done :)'
         SLACK_USERNAME: xaos613
         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }} ### full address with h>
